### PR TITLE
Player stamina

### PR DESCRIPTION
**Pull request by b-Liebenauer**
I know there is another Stamina class, but I figure we can just combine the classes and eliminate duplicates. I also noticed that my class has methods for specific actions(Dash, Heavy Attack, etc.), and has a way to subtract stamina for climbing, which the design team stated they want, which the other class (Player-stamina) has more generic methods like addStamina(), subtractStamina(), etc.

### CODE REVIEW

**Comment by b-Liebenauer** [comment]
Had to fix the ChangeStamina() method in the class. Should be good to go now.

**Review by williamhCode — COMMENTED** [review]
For the player stamina class, there's two things to note. First is that you should use time instead of frames to keep track of stamina reduction. This is a general rule of thumb in game programming, since frame rate may vary depending due to frame drops/ different hardware. Another is that the methods for accessing the Stamina class (HeavyAttack etc.) should be public so other classes can access them.

**Comment by williamhCode** [comment]
I just merged even though there's some things to work on cause there's two branches and two classes for Stamina and its a bit messy. I'll just merge the two classes and clean some stuff up cause im at the meeting rn.

**Comment by b-Liebenauer** [comment]
Cool. Just committed the changes for public methods and real time climb tracking and stamina subtraction.

**Pull request merged**
